name: diffie_hellman
description: Dart implementation of finite field Diffie-Hellman. Based on PKCS#3.
version: 1.1.0
repository: https://github.com/mrpurpleknight/diffie_hellman
homepage: https://pub.dev/packages/diffie_hellman
documentation: https://xeertz.com/diffie-hellman

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  meta: ^1.12.0
  equatable: ^2.0.5
  asn1lib: ^1.5.2

dev_dependencies:
  lints: ^3.0.0
  flutter_lints: ^3.0.1
  test: ^1.25.2