name: diffie_hellman
description: Dart implementation of finite field Diffie-Hellman. Based on PKCS#3.
version: 1.2.0
repository: https://github.com/mrpurpleknight/diffie_hellman
homepage: https://pub.dev/packages/diffie_hellman
documentation: https://xeertz.com/diffie-hellman

environment:
  sdk: ^3.4.0

dependencies:
  meta: ^1.15.0
  equatable: ^2.0.5
  asn1lib: ^1.5.3

dev_dependencies:
  lints: ^4.0.0
  flutter_lints: ^4.0.0
  test: ^1.25.2